security:
    providers:
        users_in_memory:
            memory:
                users:
                    admin:
                        roles: ['ROLE_ADMIN']
                        password: '$argon2id$v=19$m=65536,t=4,p=1$HGtPz/sHmQ1MCSn7Mlr3iQ$ZENM2smbKhn2Xyx2ySQoaCwq308CQdSnGQJqjCnMTPo' # admin123
    encoders:
        Symfony\Component\Security\Core\User\User: 'auto'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: users_in_memory
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }
